#Create a deployment by using the image pushed to Docker Hub
#Use containerPort 4200
apiVersion: apps/v1
---
#Create the service of type NodePort and use the created deployment as selector
# Use port 4200
apiVersion: v1

