#Create a deployment by using the image pushed to Docker Hub
#Use containerPort 8081
apiVersion: apps/v1
---
#Create the service of type NodePort and use the created deployment as selector
#Use port 8081
#Assign nodePort to some port in valid range, so that it can be used in angular
apiVersion: v1
